"""
Local LLM utilities for Legal Mind AI.

Uses Ollama with Llama 3.1 8B.
"""

import requests


import re
# ============================================================
# OLLAMA CONFIGURATION
# ============================================================

OLLAMA_URL = "http://localhost:11434/api/generate"

MODEL_NAME = "llama3.1:8b"


# ============================================================
# GENERAL LEGAL CHATBOT
# ============================================================



def clean_llm_formatting(text):
    """
    Remove Markdown formatting generated by the LLM
    so the frontend receives clean professional text.
    """

    if not text:
        return text

    # Remove bold / italic markers
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    text = re.sub(r'__(.*?)__', r'\1', text)

    # Remove remaining single asterisks used for bullets/italics
    text = re.sub(r'(?m)^\s*\*\s+', '- ', text)
    text = re.sub(r'(?m)^\s*-\s+', '- ', text)

    # Remove Markdown headings
    text = re.sub(r'(?m)^\s*#{1,6}\s+', '', text)

    # Remove horizontal rules
    text = re.sub(r'(?m)^\s*[-*_]{3,}\s*$', '', text)

    # Clean excessive blank lines
    text = re.sub(r'\n{3,}', '\n\n', text)

    # Remove spaces around lines
    text = '\n'.join(
        line.rstrip()
        for line in text.splitlines()
    )

    return text.strip()

def generate_answer(context, question):
    """
    Generate an answer for the general legal chatbot.

    The retrieved judgment context is used as supporting
    evidence, but the model can also use its general
    legal knowledge when the retrieved context does not
    directly answer the question.
    """

    prompt = f"""
You are Legal Mind AI, an AI assistant for legal research
focused on Indian law and Indian court judgments.

Answer the user's question clearly, accurately, and
professionally.

USER QUESTION:
{question}

RETRIEVED LEGAL CONTEXT:
{context}

INSTRUCTIONS:

1. Use the retrieved legal context as the primary evidence
   whenever it is relevant to the question.

2. If the retrieved context does not directly contain the
   answer, DO NOT say:
   "The provided judgment does not contain enough information."

3. When the retrieved context is insufficient, use your
   general legal knowledge to provide a useful answer.

4. Clearly distinguish between:
   - facts or principles found in the retrieved judgments
   - general legal knowledge or explanation

5. Do not invent case facts, court holdings, quotations,
   citations, sections, or legal authorities.

6. If you mention a specific case or legal provision, make
   sure you are confident that it is correct.

7. Do not pretend that a retrieved judgment decided an issue
   when it did not.

8. For questions involving Indian law, prefer Indian legal
   principles and terminology.

9. Explain the answer in simple but professional language.

10. When useful, structure the answer using headings,
    numbered points, or bullet points.

11. Do not use markdown symbols such as **, *, ###, or ---
    because the frontend displays the answer directly.

12. Do not provide a definitive lawyer-client legal opinion.
    Explain the legal position and mention important
    qualifications where necessary.

13. If the question is hypothetical, answer the hypothetical
    using applicable legal principles rather than pretending
    that the hypothetical facts came from a judgment.

14. If the available information is genuinely insufficient
    even after using your general legal knowledge, explain
    what information is missing instead of guessing.

Write a concise but useful answer.
""".strip()

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.2,
            "top_p": 0.9,
            "num_ctx": 8192,
            "num_predict": 1200,
        },
    }

    try:

        print("\n" + "=" * 70)
        print("GENERAL LEGAL AI")
        print("=" * 70)
        print(f"Model: {MODEL_NAME}")
        print(f"Question: {question}")
        print(f"Context characters: {len(context)}")
        print("Context window: 8192")
        print("Max output tokens: 1200")
        print("=" * 70)

        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=600,
        )

        response.raise_for_status()

        data = response.json()

        answer = (
            data.get("response")
            or ""
        ).strip()

        if not answer:
            raise RuntimeError(
                "Ollama returned an empty response."
            )

        return answer

    except requests.exceptions.Timeout:

        raise RuntimeError(
            "The AI model took too long to generate a response."
        )

    except requests.exceptions.ConnectionError:

        raise RuntimeError(
            "Unable to connect to Ollama. "
            "Make sure Ollama is running."
        )

    except requests.exceptions.RequestException as error:

        raise RuntimeError(
            f"Ollama request failed: {error}"
        )

    except Exception as error:

        raise RuntimeError(
            f"Failed to generate legal answer: {error}"
        )


# ============================================================
# JUDGMENT-SPECIFIC CHATBOT
# ============================================================

def generate_judgment_answer(
    context,
    question,
    case_name=""
):
    """
    Generate an answer about one specific judgment.

    The retrieved chunks belong only to the selected judgment.
    General legal knowledge may be used to explain the retrieved
    material, but the model must not invent facts about the case.
    """

    prompt = f"""
You are Legal Mind AI, an AI assistant helping users
understand Indian court judgments.

You are answering a question about ONE SPECIFIC JUDGMENT.

CASE:
{case_name}

USER QUESTION:
{question}

RETRIEVED PASSAGES FROM THIS JUDGMENT:
{context}

INSTRUCTIONS:

1. Treat the retrieved passages as the evidence about this
   specific judgment.

2. Answer the user's question using the retrieved passages
   whenever they contain relevant information.

3. You may use your general legal knowledge to explain legal
   concepts, terminology, sections, or principles appearing
   in the retrieved passages.

4. DO NOT invent facts, arguments, evidence, findings,
   quotations, citations, or holdings that are not supported
   by the retrieved passages.

5. If the retrieved passages do not contain a particular
   case-specific fact, do not pretend that they do.

6. If the question asks for a general legal explanation,
   provide the explanation using your legal knowledge while
   clearly keeping it separate from what this judgment says.

7. Do not respond with:
   "The provided judgment does not contain enough information"
   merely because the exact answer is not present in the
   retrieved passages.

8. Instead, give the most useful answer possible:
   - explain what the judgment establishes,
   - explain the relevant legal principle,
   - and identify any limitation in the retrieved material
     when necessary.

9. Do not attribute general legal knowledge to the court.

10. Do not claim that the court decided an issue unless the
    retrieved judgment passages support that conclusion.

11. Use simple, professional legal language.

12. Use headings, numbered points, or bullet points when
    they improve readability.

13. Do not use markdown symbols such as **, *, ###, or ---
    because the frontend displays the answer directly.

14. Do not provide a definitive lawyer-client legal opinion.

15. If the question is hypothetical, clearly identify it as
    a hypothetical and explain the relevant legal principle.

CASE-SPECIFIC RULE:
The retrieved passages are the authority for what happened
in this judgment. General legal knowledge may explain those
passages, but it must never be presented as a fact about this
case unless supported by the passages.

Write a concise and useful answer.
""".strip()

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.2,
            "top_p": 0.9,
            "num_ctx": 8192,
            "num_predict": 1200,
        },
    }

    try:

        print("\n" + "=" * 70)
        print("JUDGMENT-SPECIFIC LEGAL AI")
        print("=" * 70)
        print(f"Model: {MODEL_NAME}")
        print(f"Case: {case_name}")
        print(f"Question: {question}")
        print(f"Context characters: {len(context)}")
        print("Context window: 8192")
        print("Max output tokens: 1200")
        print("=" * 70)

        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=600,
        )

        response.raise_for_status()

        data = response.json()

        answer = (
            data.get("response")
            or ""
        ).strip()

        if not answer:
            raise RuntimeError(
                "Ollama returned an empty response."
            )

        return answer

    except requests.exceptions.Timeout:

        raise RuntimeError(
            "The AI model took too long to generate a response."
        )

    except requests.exceptions.ConnectionError:

        raise RuntimeError(
            "Unable to connect to Ollama. "
            "Make sure Ollama is running."
        )

    except requests.exceptions.RequestException as error:

        raise RuntimeError(
            f"Ollama request failed: {error}"
        )

    except Exception as error:

        raise RuntimeError(
            f"Failed to generate judgment answer: {error}"
        )


# ============================================================
# JUDGMENT SUMMARY
# ============================================================

def generate_summary(
    context,
    case_name=""
):
    """
    Generate a structured summary from retrieved judgment
    chunks.

    IMPORTANT:
    `context` should contain chunks from the selected judgment,
    preferably ordered by chunk_index.
    """

    prompt = f"""
You are Legal Mind AI, an AI assistant specialized in
understanding Indian court judgments.

Create a clear and professional summary of the following
judgment.

CASE:
{case_name}

JUDGMENT CONTEXT:
{context}

Create the summary using these sections:

OVERVIEW

KEY FACTS

LEGAL ISSUES

PARTIES' ARGUMENTS

COURT'S REASONING

FINAL DECISION

KEY TAKEAWAYS

INSTRUCTIONS:

1. Base case-specific statements on the supplied judgment
   context.

2. Preserve the meaning of the court's reasoning and decision.

3. Do not invent facts or legal findings.

4. If some information is not available in the supplied
   context, do not fabricate it.

5. Use general legal knowledge only when necessary to explain
   terminology or legal concepts.

6. Do not attribute general legal knowledge to the court.

7. Make the summary understandable to a student, researcher,
   lawyer, or ordinary reader.

8. Keep important names, legal provisions, dates, and
   conclusions when they are available in the context.

9. Do not make the summary unnecessarily long.

10. Do not use markdown symbols such as **, *, ###, or ---
    because the frontend displays the result directly.

11. Use plain section headings such as:

OVERVIEW
KEY FACTS
LEGAL ISSUES
PARTIES' ARGUMENTS
COURT'S REASONING
FINAL DECISION
KEY TAKEAWAYS

12. Under each heading, use clear paragraphs or simple
    bullet-style sentences.

13. Do not provide a definitive lawyer-client legal opinion.

Return only the summary.
""".strip()

    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.2,
            "top_p": 0.9,
            "num_ctx": 8192,
            "num_predict": 1400,
        },
    }

    try:

        print("\n" + "=" * 70)
        print("JUDGMENT SUMMARY")
        print("=" * 70)
        print(f"Model: {MODEL_NAME}")
        print(f"Case: {case_name}")
        print(f"Context characters: {len(context)}")
        print("Context window: 8192")
        print("Max output tokens: 1400")
        print("=" * 70)

        response = requests.post(
            OLLAMA_URL,
            json=payload,
            timeout=600,
        )

        response.raise_for_status()

        data = response.json()

        summary = (
            data.get("response")
            or ""
        ).strip()

        if not summary:
            raise RuntimeError(
                "Ollama returned an empty summary."
            )

        return summary

    except requests.exceptions.Timeout:

        raise RuntimeError(
            "The AI model took too long to generate the summary."
        )

    except requests.exceptions.ConnectionError:

        raise RuntimeError(
            "Unable to connect to Ollama. "
            "Make sure Ollama is running."
        )

    except requests.exceptions.RequestException as error:

        raise RuntimeError(
            f"Ollama request failed: {error}"
        )

    except Exception as error:

        raise RuntimeError(
            f"Failed to generate summary: {error}"
        )